// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index(Props) {
  return React.createElement("div", undefined, "PURE PERCY TEST");
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
