// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index(Props) {
  var children = Props.children;
  console.log(children);
  return React.createElement("div", undefined);
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
