// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Pane(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, children);
}

var make = Pane;

export {
  make ,
  
}
/* react Not a pure module */
