// Generated by ReScript, PLEASE EDIT WITH CARE


var isElementTypeEqual = ((element, toCompare) => element.type === toCompare);

var getInitialSize = ((element) => element.props.initialSize);

export {
  isElementTypeEqual ,
  getInitialSize ,
  
}
/* No side effect */
