// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(props, children) {
  return React.cloneElement(children, props);
}

export {
  make ,
  
}
/* react Not a pure module */
